create extension if not exists pgcrypto;

create table if not exists public.teacher_accounts (
  id uuid primary key default gen_random_uuid(),
  login text not null unique,
  password_hash text not null,
  display_name text not null default 'Учитель',
  created_at timestamptz not null default now()
);

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  name text not null,
  login text not null unique,
  password_hash text not null,
  invite_code text not null unique,
  subjects text[] not null default '{}',
  exams text[] not null default '{}',
  last_activity text not null default 'Еще не заходил',
  completed_tasks integer not null default 0,
  average_score integer not null default 0 check (average_score between 0 and 100),
  created_at timestamptz not null default now()
);

create table if not exists public.invitations (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  created_by uuid references public.teacher_accounts(id) on delete set null,
  used_by bigint references public.students(id) on delete set null,
  is_used boolean not null default false,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.teacher_accounts enable row level security;
alter table public.students enable row level security;
alter table public.invitations enable row level security;

drop policy if exists "Allow public read for prototype students" on public.students;
drop policy if exists "Allow public read for prototype invitations" on public.invitations;
alter table public.teacher_accounts add column if not exists session_version integer not null default 0;
revoke all on public.teacher_accounts, public.students, public.invitations from anon, authenticated;

create or replace function public.verify_teacher_login(input_login text, input_password text)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.teacher_accounts
    where login = input_login
      and password_hash = extensions.crypt(input_password, password_hash)
  );
$$;

revoke all on function public.verify_teacher_login(text, text) from public;
revoke execute on function public.verify_teacher_login(text, text) from anon, authenticated;

create index if not exists invitations_created_at_idx on public.invitations (created_at desc);
