create extension if not exists pgcrypto;

create table if not exists public.teacher_accounts (
  id uuid primary key default gen_random_uuid(),
  login text not null unique,
  password_hash text not null,
  display_name text not null default 'Учитель',
  created_at timestamptz not null default now()
);

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  name text not null,
  login text not null unique,
  password_hash text not null,
  invite_code text not null unique,
  subjects text[] not null default '{}',
  exams text[] not null default '{}',
  last_activity text not null default 'Еще не заходил',
  completed_tasks integer not null default 0,
  average_score integer not null default 0 check (average_score between 0 and 100),
  created_at timestamptz not null default now()
);

create table if not exists public.invitations (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  created_by uuid references public.teacher_accounts(id) on delete set null,
  used_by bigint references public.students(id) on delete set null,
  is_used boolean not null default false,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.teacher_accounts enable row level security;
alter table public.students enable row level security;
alter table public.invitations enable row level security;

drop policy if exists "Allow public read for prototype students" on public.students;
create policy "Allow public read for prototype students"
  on public.students
  for select
  using (true);

drop policy if exists "Allow public read for prototype invitations" on public.invitations;
create policy "Allow public read for prototype invitations"
  on public.invitations
  for select
  using (true);

insert into public.teacher_accounts (login, password_hash, display_name)
values ('TestTeacher', crypt('123321', gen_salt('bf')), 'TestTeacher')
on conflict (login) do nothing;

insert into public.students
  (name, login, password_hash, invite_code, subjects, exams, last_activity, completed_tasks, average_score)
values
  ('Алина Морозова', 'student_alina', crypt('Q7v!2mZp#19a', gen_salt('bf')), 'LZ-8K2P-MR91', array['История', 'Обществознание'], array['ЕГЭ'], 'Сегодня', 42, 78),
  ('Матвей Орлов', 'student_matvey', crypt('N4r$8xTc@52q', gen_salt('bf')), 'LZ-3Q7N-OL44', array['История'], array['ОГЭ'], 'Вчера', 18, 64),
  ('София Белова', 'student_sofia', crypt('H9p&6dVy!03s', gen_salt('bf')), 'LZ-6B1S-BL28', array['Обществознание'], array['ЕГЭ'], '2 дня назад', 35, 82),
  ('Иван Соколов', 'student_ivan', crypt('R2k#9wLp$74f', gen_salt('bf')), 'LZ-5V8D-SK63', array['История', 'Обществознание'], array['ОГЭ', 'ЕГЭ'], 'Сегодня', 51, 71),
  ('Ева Кузнецова', 'student_eva', crypt('T8z!1qMa#66u', gen_salt('bf')), 'LZ-2C4E-KZ10', array['Обществознание'], array['ОГЭ'], '5 дней назад', 11, 58),
  ('Даниил Волков', 'student_daniil', crypt('M6y$3hXn@81p', gen_salt('bf')), 'LZ-9H5W-VK37', array['История'], array['ЕГЭ'], 'Сегодня', 27, 69),
  ('Мария Федорова', 'student_maria', crypt('P1s&7jRb!48k', gen_salt('bf')), 'LZ-1F6M-FD82', array['История', 'Обществознание'], array['ЕГЭ'], '3 дня назад', 63, 87),
  ('Артем Новиков', 'student_artem', crypt('V5c#0nGt$25e', gen_salt('bf')), 'LZ-7A3T-NV55', array['Обществознание'], array['ЕГЭ'], 'Неделю назад', 9, 49)
on conflict (login) do nothing;

insert into public.invitations (code)
values
  ('LZ-8K2P-MR91'),
  ('LZ-3Q7N-OL44'),
  ('LZ-6B1S-BL28'),
  ('LZ-5V8D-SK63'),
  ('LZ-2C4E-KZ10'),
  ('LZ-9H5W-VK37'),
  ('LZ-1F6M-FD82'),
  ('LZ-7A3T-NV55')
on conflict (code) do nothing;
